# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/shared/proto/bomberman_ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/shared/proto/bomberman_ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#app/shared/proto/bomberman_ai.proto\x12\tbomberman\"\x16\n\x14TrainingStartRequest\"\x17\n\x15TrainingStartResponse\"8\n\x0bObservation\x12\x13\n\x0bgrid_values\x18\x01 \x03(\x02\x12\x14\n\x0cstats_values\x18\x02 \x03(\x02\"x\n\x14TrainingResetRequest\x12\x11\n\tmap_width\x18\x01 \x01(\x05\x12\x12\n\nmap_height\x18\x02 \x01(\x05\x12\x13\n\x0b\x65nemy_count\x18\x03 \x01(\x05\x12\x16\n\x0e\x65nable_enemies\x18\x04 \x01(\x08\x12\x0c\n\x04seed\x18\x05 \x01(\x05\"k\n\x15TrainingResetResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12+\n\x0bobservation\x18\x02 \x01(\x0b\x32\x16.bomberman.Observation\x12\x11\n\tinfo_json\x18\x03 \x01(\t\"P\n\x13TrainingStepRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\x05\x12\x15\n\rdelta_seconds\x18\x03 \x01(\x02\"\x8d\x01\n\x14TrainingStepResponse\x12+\n\x0bobservation\x18\x01 \x01(\x0b\x32\x16.bomberman.Observation\x12\x0e\n\x06reward\x18\x02 \x01(\x02\x12\x12\n\nterminated\x18\x03 \x01(\x08\x12\x11\n\ttruncated\x18\x04 \x01(\x08\x12\x11\n\tinfo_json\x18\x05 \x01(\t\"h\n\x12InferActionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12+\n\x0bobservation\x18\x03 \x01(\x0b\x32\x16.bomberman.Observation\"%\n\x13InferActionResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x32\xa2\x01\n\x0bGameService\x12J\n\x05Reset\x12\x1f.bomberman.TrainingResetRequest\x1a .bomberman.TrainingResetResponse\x12G\n\x04Step\x12\x1e.bomberman.TrainingStepRequest\x1a\x1f.bomberman.TrainingStepResponse2\xad\x01\n\tAIService\x12R\n\rStartTraining\x12\x1f.bomberman.TrainingStartRequest\x1a .bomberman.TrainingStartResponse\x12L\n\x0bInferAction\x12\x1d.bomberman.InferActionRequest\x1a\x1e.bomberman.InferActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.shared.proto.bomberman_ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAININGSTARTREQUEST']._serialized_start=50
  _globals['_TRAININGSTARTREQUEST']._serialized_end=72
  _globals['_TRAININGSTARTRESPONSE']._serialized_start=74
  _globals['_TRAININGSTARTRESPONSE']._serialized_end=97
  _globals['_OBSERVATION']._serialized_start=99
  _globals['_OBSERVATION']._serialized_end=155
  _globals['_TRAININGRESETREQUEST']._serialized_start=157
  _globals['_TRAININGRESETREQUEST']._serialized_end=277
  _globals['_TRAININGRESETRESPONSE']._serialized_start=279
  _globals['_TRAININGRESETRESPONSE']._serialized_end=386
  _globals['_TRAININGSTEPREQUEST']._serialized_start=388
  _globals['_TRAININGSTEPREQUEST']._serialized_end=468
  _globals['_TRAININGSTEPRESPONSE']._serialized_start=471
  _globals['_TRAININGSTEPRESPONSE']._serialized_end=612
  _globals['_INFERACTIONREQUEST']._serialized_start=614
  _globals['_INFERACTIONREQUEST']._serialized_end=718
  _globals['_INFERACTIONRESPONSE']._serialized_start=720
  _globals['_INFERACTIONRESPONSE']._serialized_end=757
  _globals['_GAMESERVICE']._serialized_start=760
  _globals['_GAMESERVICE']._serialized_end=922
  _globals['_AISERVICE']._serialized_start=925
  _globals['_AISERVICE']._serialized_end=1098
# @@protoc_insertion_point(module_scope)
