version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1

  backend-fastapi:
    build:
      context: ./
      dockerfile: ./server2/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./server2:/app/server2
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development


  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-bomberman}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-bomberman}
      - POSTGRES_DB=${POSTGRES_DB:-bomberman}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
