version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1

  backend-fastapi:
    build:
      context: ./
      dockerfile: ./server2/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./server2:/app/server2
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development

