[project]
name = "bombermanonline"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "eventlet>=0.39.1",
    "flask>=3.1.0",
    "flask-socketio>=5.5.1",
    "python-engineio>=4.12.0",
    "python-socketio>=5.13.0",
]
